<?php
/**
 * Template name: Upload Redirect
 */

// Check that the nonce is valid, and the user can edit this post.
$m = new \Stds\Types\MediaHandlerSettings();
$aj = new \Stds\Types\AjaxDefs();
if ( 
    isset( $_POST[$m::MEDIA_FILE_UPLOAD_FIELD."_nonce"] ) 
    //isset( $_POST[$m::MEDIA_FILE_UPLOAD_FIELD."_nonce"], $_POST['post_id'] ) 
	&& wp_verify_nonce( $_POST[$m::MEDIA_FILE_UPLOAD_FIELD."_nonce"], $m::MEDIA_FILE_UPLOAD_FIELD)
	//&& current_user_can( 'edit_post', $_POST['post_id'] )
) {
    if ( ! function_exists( 'wp_handle_upload' ) ) {
        require_once( ABSPATH . 'wp-admin/includes/file.php' );
    }
    
    $uploadedfile = $_FILES[$m::MEDIA_FILE_UPLOAD_FIELD];

    //$upload_overrides= ['action' => "http://transfer.tab4lioz.beget.tech/upload-redir/"];
    $upload_overrides = ['test_form' => false];
    $dir = wp_upload_dir();
    $media_upload_dir = function($param) use ($dir){
        $uploadDir = '/uploads';
        $url = $dir['baseurl'].$uploadDir;
        $dir = $dir['basedir'].$uploadDir;
        $param['path'] = $dir;
        $param['url']=$url;

        return $param;
    };
    add_filter('upload_dir',$media_upload_dir);
    $movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
    if ( $movefile && ! isset( $movefile['error'] ) ) {
        $redirUrl = $_REQUEST[$m::REDIR_COMEBACK_URL.'_'];
        $redirUrl = sanitize_text_field($redirUrl);
        $query = [
            $aj::CARGO => [
                'option' => $aj::GET_MEDIA_VIEWER
            ]
        ];
        $query = http_build_query($query);
        if( wp_redirect($redirUrl."?".$query)){
                exit;
        }
    } else {
        /* @TODO to add redirect to some default page */
        /**
         * Error generated by _wp_handle_upload()
         * @see _wp_handle_upload() in wp-admin/includes/file.php
         */
        echo $movefile['error'];
    }


	// The nonce was valid and the user has the capabilities, it is safe to continue.

    // These files need to be included as dependencies when on the front end.
    /*
	require_once( ABSPATH . 'wp-admin/includes/image.php' );
	//require_once( ABSPATH . 'wp-admin/includes/file.php' );
	require_once( ABSPATH . 'wp-admin/includes/media.php' );
	pr(UPLOADS);
	// Let WordPress handle the upload.
	// Remember, 'my_image_upload' is the name of our file input in our form above.
    //$attachment_id = media_handle_upload( $media::MEDIA_FILE_UPLOAD_FIELD, $_POST['post_id'] );
    $attachment_id = media_handle_upload( $m::MEDIA_FILE_UPLOAD_FIELD,0 );
	
	if ( is_wp_error( $attachment_id ) ) {
        pr($attachment_id);
		// There was an error uploading the image.
	} else {
        echo 'success';
		// The image was uploaded successfully!
	}*/

} else {

	// The security check failed, maybe show the user an error.
}